# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tomster12/files/EMBS/vivado/vivado.srcs/sources_1/bd/zybo_design/ip/zybo_design_auto_us_0/zybo_design_auto_us_0.xci
# IP: The module: 'zybo_design_auto_us_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tomster12/files/EMBS/vivado/vivado.gen/sources_1/bd/zybo_design/ip/zybo_design_auto_us_0/zybo_design_auto_us_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_design_auto_us_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tomster12/files/EMBS/vivado/vivado.gen/sources_1/bd/zybo_design/ip/zybo_design_auto_us_0/zybo_design_auto_us_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_design_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/tomster12/files/EMBS/vivado/vivado.srcs/sources_1/bd/zybo_design/ip/zybo_design_auto_us_0/zybo_design_auto_us_0.xci
# IP: The module: 'zybo_design_auto_us_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tomster12/files/EMBS/vivado/vivado.gen/sources_1/bd/zybo_design/ip/zybo_design_auto_us_0/zybo_design_auto_us_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_design_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/tomster12/files/EMBS/vivado/vivado.gen/sources_1/bd/zybo_design/ip/zybo_design_auto_us_0/zybo_design_auto_us_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_design_auto_us_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
