# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tomster12/files/EMBS/vivado/vivado.srcs/sources_1/bd/zybo_design/ip/zybo_design_processing_system7_0_6/zybo_design_processing_system7_0_6.xci
# IP: The module: 'zybo_design_processing_system7_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tomster12/files/EMBS/vivado/vivado.gen/sources_1/bd/zybo_design/ip/zybo_design_processing_system7_0_6/zybo_design_processing_system7_0_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_design_processing_system7_0_6'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/tomster12/files/EMBS/vivado/vivado.srcs/sources_1/bd/zybo_design/ip/zybo_design_processing_system7_0_6/zybo_design_processing_system7_0_6.xci
# IP: The module: 'zybo_design_processing_system7_0_6' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tomster12/files/EMBS/vivado/vivado.gen/sources_1/bd/zybo_design/ip/zybo_design_processing_system7_0_6/zybo_design_processing_system7_0_6.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_design_processing_system7_0_6'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
