
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2020.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2025 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xtoplevel.h"

/*
* The configuration table for devices
*/

XToplevel_Config XToplevel_ConfigTable[XPAR_XTOPLEVEL_NUM_INSTANCES] =
{
	{
		XPAR_TOPLEVEL_0_DEVICE_ID,
		XPAR_TOPLEVEL_0_S_AXI_AXILITES_BASEADDR,
		XPAR_TOPLEVEL_0_S_AXI_CONTROL_BASEADDR
	}
};


