# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/userfs/t/tb1262/Files/EMBS/embs-assessment/vivado/vivado.srcs/sources_1/bd/zybo_design/ip/zybo_design_auto_pc_2/zybo_design_auto_pc_2.xci
# IP: The module: 'zybo_design_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/userfs/t/tb1262/Files/EMBS/embs-assessment/vivado/vivado.gen/sources_1/bd/zybo_design/ip/zybo_design_auto_pc_2/zybo_design_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_design_auto_pc_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/userfs/t/tb1262/Files/EMBS/embs-assessment/vivado/vivado.srcs/sources_1/bd/zybo_design/ip/zybo_design_auto_pc_2/zybo_design_auto_pc_2.xci
# IP: The module: 'zybo_design_auto_pc_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/userfs/t/tb1262/Files/EMBS/embs-assessment/vivado/vivado.gen/sources_1/bd/zybo_design/ip/zybo_design_auto_pc_2/zybo_design_auto_pc_2_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zybo_design_auto_pc_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
