#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : zybo_design.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Mon May 05 19:46:24 BST 2025
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: zybo_design.sh [-help]
# usage: zybo_design.sh [-lib_map_path]
# usage: zybo_design.sh [-noclean_files]
# usage: zybo_design.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'zybo_design.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm axi_infrastructure_v1_1_0 axi_vip_v1_1_8 processing_system7_vip_v1_0_10 xil_defaultlib generic_baseblocks_v2_1_0 axi_register_slice_v2_1_22 fifo_generator_v13_2_5 axi_data_fifo_v2_1_21 axi_crossbar_v2_1_23 lib_cdc_v1_0_2 proc_sys_reset_v5_0_13 lib_pkg_v1_0_2 lib_fifo_v1_0_14 blk_mem_gen_v8_4_4 lib_bmg_v1_0_13 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_24 axi_vdma_v6_3_10 axi_lite_ipif_v3_0_4 v_tc_v6_2_1 v_tc_v6_1_13 v_vid_in_axi4s_v4_0_9 v_axi4s_vid_out_v4_0_11 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_22 axis_subset_converter_v1_1_22 xlconstant_v1_1_7 axi_protocol_converter_v2_1_22 axi_clock_converter_v2_1_21 axi_dwidth_converter_v2_1_22 axi_mmu_v2_1_20)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "zybo_design.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "/opt/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "/opt/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "/opt/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "/opt/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_vip_v1_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/94c3/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_10 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_processing_system7_0_3/sim/zybo_design_processing_system7_0_3.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/54c0/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_23 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/bc0a/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_xbar_3/sim/zybo_design_xbar_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_rst_ps7_0_50M_0/sim/zybo_design_rst_ps7_0_50M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_xbar_4/sim/zybo_design_xbar_4.v" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/9097/src/mmcme2_drp.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/9097/src/axi_dynclk_S00_AXI.vhd" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/9097/src/axi_dynclk.vhd" \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_axi_dynclk_0_2/sim/zybo_design_axi_dynclk_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_13 $vhdlan_opts \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/af67/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_24 $vhdlan_opts \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/4ab6/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_3_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl/axi_vdma_v6_3_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_3_10 $vhdlan_opts \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl/axi_vdma_v6_3_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_axi_vdma_0_2/sim/zybo_design_axi_vdma_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_2_1 $vhdlan_opts \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/cd2e/hdl/v_tc_v6_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_v_tc_0_2/sim/zybo_design_v_tc_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_13 $vhdlan_opts \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/b92e/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_vid_in_axi4s_v4_0_9 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/b2aa/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_axi4s_vid_out_v4_0_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/1a1e/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_v_axi4s_vid_out_0_2/sim/zybo_design_v_axi4s_vid_out_0_2.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/20df/src/ClockGen.vhd" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/20df/src/SyncAsync.vhd" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/20df/src/SyncAsyncReset.vhd" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/20df/src/DVI_Constants.vhd" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/20df/src/OutputSERDES.vhd" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/20df/src/TMDS_Encoder.vhd" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/20df/src/rgb2dvi.vhd" \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_rgb2dvi_0_2/sim/zybo_design_rgb2dvi_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ebcc/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_axis_subset_converter_0_2/hdl/tdata_zybo_design_axis_subset_converter_0_2.v" \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_axis_subset_converter_0_2/hdl/tuser_zybo_design_axis_subset_converter_0_2.v" \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_axis_subset_converter_0_2/hdl/tstrb_zybo_design_axis_subset_converter_0_2.v" \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_axis_subset_converter_0_2/hdl/tkeep_zybo_design_axis_subset_converter_0_2.v" \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_axis_subset_converter_0_2/hdl/tid_zybo_design_axis_subset_converter_0_2.v" \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_axis_subset_converter_0_2/hdl/tdest_zybo_design_axis_subset_converter_0_2.v" \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_axis_subset_converter_0_2/hdl/tlast_zybo_design_axis_subset_converter_0_2.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_subset_converter_v1_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/69d9/hdl/axis_subset_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_axis_subset_converter_0_2/hdl/top_zybo_design_axis_subset_converter_0_2.v" \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_axis_subset_converter_0_2/sim/zybo_design_axis_subset_converter_0_2.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_xlconstant_0_2/sim/zybo_design_xlconstant_0_2.v" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/d708/hdl/verilog/toplevel_a_star_len.v" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/d708/hdl/verilog/toplevel_a_star_len_closed_set.v" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/d708/hdl/verilog/toplevel_a_star_len_open_set_heap_f_score.v" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/d708/hdl/verilog/toplevel_AXILiteS_s_axi.v" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/d708/hdl/verilog/toplevel_control_s_axi.v" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/d708/hdl/verilog/toplevel_local_ram.v" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/d708/hdl/verilog/toplevel_mac_muladd_16ns_16ns_16ns_18_4_1.v" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/d708/hdl/verilog/toplevel_MAXI_m_axi.v" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/d708/hdl/verilog/toplevel_mul_mul_16ns_16ns_18_4_1.v" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/d708/hdl/verilog/toplevel_mul_mul_16ns_16ns_32_4_1.v" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/d708/hdl/verilog/toplevel_waypoints_x.v" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/d708/hdl/verilog/toplevel.v" \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_toplevel_0_1/sim/zybo_design_toplevel_0_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/5cee/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_auto_pc_0/sim/zybo_design_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/1304/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/2394/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_auto_us_0/sim/zybo_design_auto_us_0.v" \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_auto_pc_1/sim/zybo_design_auto_pc_1.v" \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_auto_pc_2/sim/zybo_design_auto_pc_2.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_mmu_v2_1_20 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/88c9/hdl/axi_mmu_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/7860/hdl" +incdir+"$ref_dir/../../../../vivado.gen/sources_1/bd/zybo_design/ipshared/8713/hdl" +incdir+"/opt/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_s00_mmu_0/sim/zybo_design_s00_mmu_0.v" \
    "$ref_dir/../../../bd/zybo_design/ip/zybo_design_s01_mmu_0/sim/zybo_design_s01_mmu_0.v" \
    "$ref_dir/../../../bd/zybo_design/sim/zybo_design.v" \
  2>&1 | tee -a vlogan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.zybo_design xil_defaultlib.glbl -o zybo_design_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./zybo_design_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./zybo_design.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  else
    lib_map_path="/home/tomster12/files/EMBS/vivado/vivado.cache/compile_simlib/vcs"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key zybo_design_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc zybo_design_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./zybo_design.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: zybo_design.sh [-help]\n\
Usage: zybo_design.sh [-lib_map_path]\n\
Usage: zybo_design.sh [-reset_run]\n\
Usage: zybo_design.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
